# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/raizes_nordeste
spring.datasource.username=postgres
spring.datasource.password=1234

# ===============================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================
# Atualiza as tabelas automaticamente baseado nas suas classes Java (Ideal para o desenvolvimento)
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostra o SQL no console (Ótimo para debugar e comprovar que está funcionando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=minha-chave-123
